data:
  max_freq: 16000.0
  num_freq_bin: 128
  fs_up: 384000.0
  hutubs:
    path: "./data/hutubs"
    sub_id:
      train: [0, 77]
      valid: [77, 87]
      test:  [88, 95]
    front_id: 202
  riec:
    path: "./data/riec"
    sub_id:
      train: [0, 86]
      valid: [86, 97]
      test:  [97, 105]
    front_id: 216

training:
  num_mes_pos_train: ["all", 256, 169, 100, 49, 16, 9, 6, 4]

swfe:
  hrtf:
    reg_param: 0.000001
    coeff: 2.0
    sound_speed: 343.18
    r_shoulder: 0.45

rshe:
  hrtf_mag:
    reg_param: 0.001
    coeff: 2.0
  itd:
    reg_param: 0.000001
    coeff: 0.5

spca:
  hrtf_mag:
    reg_param: 0.001
    coeff: 0.5
